### ISSUE TITLE
Not finding selections for the attached vendors.

### ISSUE THREAD

**Issue by wian-lloyd** [wian-lloyd/racecard-tip-extractor#1]
Attached are files were used.
[WARRAGULAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922683/WARRAGULAUS2022.10.10.pdf)
[TAMWORTHAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922684/TAMWORTHAUS2022.10.10.pdf)
[REDCLIFFEAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922685/REDCLIFFEAUS2022.10.10.pdf)
[PINJARRAAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922686/PINJARRAAUS2022.10.10.pdf)
[NEWCASTLE_HARNESSAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922687/NEWCASTLE_HARNESSAUS2022.10.10.pdf)
[MURWILLUMBAHAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922688/MURWILLUMBAHAUS2022.10.10.pdf)
[GLOBE_DERBYAUS2022.10.10.pdf](https://github.com/wian-lloyd/racecard-tip-extractor/files/9922689/GLOBE_DERBYAUS2022.10.10.pdf)

**Comment by Spikes-za** [comment]
Hi Wian,
I will try out the software again today and see what it does.Thank you

**Comment by wian-lloyd** [comment]
Working, for now. 🎉
